double result = calibrer(MIN_RAW);
TEST_ASSERT_DOUBLE_EQ(MIN_ANGLE, result, 0.001); 
double result = calibrer(MAX_RAW);
TEST_ASSERT_DOUBLE_EQ(MAX_ANGLE, result, 0.001);
int mid_raw = (MIN_RAW + MAX_RAW) / 2;
double result = calibrer(mid_raw);
TEST_ASSERT_DOUBLE_EQ(0.0, result, 0.5);
double result_below = calibrer(MIN_RAW - 100);
double result_above = calibrer(MAX_RAW + 100);
TEST_ASSERT_DOUBLE_EQ(0.0, result_below, 0.001);
TEST_ASSERT_DOUBLE_EQ(0.0, result_above, 0.001);
double x, y;
calculer_position(0.0, &x, &y);
TEST_ASSERT_DOUBLE_EQ(OFFSET_X + L_HAND, x, 0.001);
TEST_ASSERT_DOUBLE_EQ(OFFSET_Y, y, 0.001);
double x, y;
calculer_position(90.0, &x, &y);
TEST_ASSERT_DOUBLE_EQ(OFFSET_X, x, 0.001);
TEST_ASSERT_DOUBLE_EQ(OFFSET_Y + L_HAND, y, 0.001);
double angle = calculer_angle(OFFSET_X + L_HAND, OFFSET_Y);
TEST_ASSERT_DOUBLE_EQ(0.0, angle, 0.001);